### PR TITLE
Move BaseFormSet test to within form_collection loop.

### PR DESCRIPTION
**Pull request by halfnibble**
Fixes issue #5. Basically, I moved the BaseFormSet test to within the form_collection loop because you may have a dict containing a formset, which would never see the elif test statement in the original code. 

(Note: I have not added any new tests).

### CODE REVIEW

**Comment by halfnibble** [comment]
Ah yes, I missed that form_collection starts out as an empty array. Good catch.

**Comment by halfnibble** [comment]
Ok, so the code may look a little redundant, but it should cover all scenarios. I added back the original formset test, and kept the formset test within the form_collection loop (to handle a scenario whereby a dict contains a formset). Something cleaner may require more re-factoring--which I don't feel familiar enough with the codebase to do at this point.

**Comment by dirkmoors** [comment]
Ok thanks, i don't see any direct issues with that, I'll merge!

**Comment by SebCorbin** [comment]
Would it be possible to tag this commit so we can use it on a stable version ?

**Pull request merged**
